Kui branch
SPS-Team22-2020Spring/pincident pull request #35
Opened 2021-04-07 01:31 UTC by Kuiiii

Autocomplete and search box

2021-04-07 01:48 UTC, Valentinagrando submitted a review, later dismissed

2021-04-07 02:46 UTC, CarloLj requested changes
The post method is not working. Consider using the post method that I used in my branch and ajax, copy and paste my method and my servlet response :). 

I love the fly part :), change the name of the pin "marker", that's why the error message: "Assignment to constant variable." is showing.

2021-04-09 05:58 UTC, CarloLj approved these changes, later dismissed
I'll do the necessary changes..

Ok.

2021-04-09 06:00 UTC, CarloLj approved these changes

2021-04-09 06:04 UTC, merged